spring:
  application:
    name: CustomerServer

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/TMDT}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: ${SERVER_PORT:8083}

aws:
  access-key: ${AWS_ACCESS_KEY_ID:test}
  secret-key: ${AWS_SECRET_ACCESS_KEY:test}
  region: ap-southeast-1
  bucket-name: my-test-bucket
  endpoint: http://localhost:4566

# LOCALSTACK_ENDPOINT: http://localhost:4566