spring:
  application:
    name: CustomerServer

  datasource:
    # url: ${DB_URL:jdbc:postgresql://localhost:5432/TMDT}
    # username: ${DB_USERNAME:postgres}
    # password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: ${SERVER_PORT:8083}

aws:
  access-key: ${AWS_ACCESS_KEY_ID:test}
  secret-key: ${AWS_SECRET_ACCESS_KEY:test}
  region: us-east-1
  secret-name: dev
  endpoint: http://localhost:4566
