services:
  seller-client:
    build:
      context: ./clients
      dockerfile: dockerfile
      args:
        - VITE_MODE=seller-prod
    ports:
      - "80:80"
    # environment:
    #   - NODE_ENV=production
    #   - VITE_SERVER_URL=http://seller-server:8080
    volumes:
      - ./clients/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - seller-server
    networks:
      - expose

  customer-client:
    build:
      context: ./clients
      dockerfile: dockerfile
      args:
        - VITE_MODE=customer-prod
    ports:
      - "81:80"
    # environment:
    #   - NODE_ENV=production
    #   - VITE_SERVER_URL=http://customer-server:8081
    volumes:
      - ./clients/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - customer-server
    networks:
      - expose

  customer-server:
    container_name: customer-server
    build:
      context: ./server
      dockerfile: dockerfile.customer
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/TMDT
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL-AUTO=none
      - SERVER_PORT=8081
      - AWS_ACCESS-KEY=test
      - AWS_SECRET-KEY=test
      - AWS_REGION=test
      - AWS_SECRET-NAME=prod
      - AWS_ENDPOINT=http://localstack:4566
    depends_on:
      - database
      - localstack
    networks:
      - expose
      - database
      - localstack

  seller-server:
    container_name: seller-server
    build:
      context: ./server
      dockerfile: dockerfile.seller
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # AWS
      - AWS__Profile=default
      - AWS__RegionEndpoint=us-east-1
      - AWS__AccessKey=test
      - AWS__SecretKey=test
      - AWS__UseLocalStack=true
      - AWS__SecretName=prod/credentials
      - AWS__ServiceURL=http://localstack:4566
    depends_on:
      - database
      - localstack
    networks:
      - expose
      - database
      - localstack

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - 4566:4566 # main edge endpoint for all services
      - 4571:4571
    environment:
      # Enable all AWS free-tier services (you can add/remove as needed)
      - SERVICES=s3,lambda,sqs,sns,dynamodb,cloudwatch,cloudformation,iam,sts,events,secretsmanager,ssm
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack # persist service state
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LOCALSTACK_HOST=localstack
      - LAMBDA_EXECUTOR=docker
      - HOST_TMP_FOLDER=/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=1
    volumes:
      # persist all data locally
      - ./localstack-data:/var/lib/localstack
      # allow LocalStack to spawn Docker containers for Lambdas
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - localstack

  database:
    container_name: database
    image: postgres:17.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: TMDT
    ports:
      - 5000:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - database

volumes:
  db-data:
  localstack-data:

networks:
  expose:
  database:
  localstack:
